import { Recipe } from './recipe';

export const RECIPES: Recipe[] = [
    {
        _id: "1",
        group: 3,
        name: "Pavé de saumon",
        difficulty: 1,
        duration: 20,
        serving: 1,
        type: 'url',
        deletedAt: -1,
    },
    {
        _id: "2",
        group: 3,
        name: "Pavé de saumon",
        difficulty: 1,
        duration: 20,
        serving: 1,
        type: 'url',
        deletedAt: -1,
    },
    {
        _id: "3",
        group: 3,
        name: "Pavé de saumon",
        difficulty: 1,
        duration: 20,
        serving: 1,
        type: 'url',
        deletedAt: -1,
    },
    {
        _id: "4",
        group: 3,
        name: "Pavé de saumon",
        difficulty: 1,
        duration: 20,
        serving: 1,
        type: 'url',
        deletedAt: -1,
    },
    {
        _id: "5",
        group: 3,
        name: "Pavé de saumon",
        difficulty: 1,
        duration: 20,
        serving: 1,
        type: 'url',
        deletedAt: -1,
    },
    {
        _id: "6",
        group: 3,
        name: "Pavé de saumon",
        difficulty: 1,
        duration: 20,
        serving: 1,
        type: 'url',
        deletedAt: -1,
    }
]
